### ISSUE TITLE
Support for 2FA login

### ISSUE THREAD

**Issue by FMGordillo** [bstarling/gh-labels-template#1]
# Description
As the [`Github Developer Portal`](https://developer.github.com/v3/auth/#working-with-two-factor-authentication) indicates, password authentication to the API will be discouraged. Even worse, with 2FA.

# Screenshot
![Screen Shot 2020-04-15 at 12 10 55](https://user-images.githubusercontent.com/7970174/79353967-2aa7cb80-7f12-11ea-8f4c-29f2d88fd3c3.png)

**Comment by bstarling** [comment]
Thanks for your interest. You should generate a personal access token and use that. You can delete it from your profile at any time. That said, this tool has not been used or updated in a long time so use at your own risk!  https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
